= To install

* `mvn install`

== To set containers

We need three containers

* `export JBOSS_HOME_1=$PWD/jboss-eap-7.0-1`
* `export JBOSS_HOME_2=$PWD/jboss-eap-7.0-2`
* `export JBOSS_HOME_3=$PWD/jboss-eap-7.0-3`

or

* `export JBOSS_HOME_1=$PWD/jboss-eap-7.0.0.ER3-1`
* `export JBOSS_HOME_2=$PWD/jboss-eap-7.0.0.ER3-2`
* `export JBOSS_HOME_3=$PWD/jboss-eap-7.0.0.ER3-3`

or

* `export JBOSS_HOME_1=$PWD/jboss-eap-6.4-1`
* `export JBOSS_HOME_2=$PWD/jboss-eap-6.4-2`
* `export JBOSS_HOME_3=$PWD/jboss-eap-6.4-3`


Define EAP settings

* adding application user for security connection
* system property `call.port` which is used for knowing how behave
* transaction node identifier defined
* outbound connection is needed

```
for I in `seq 1 3`; do
  JBOSS_HOME=`echo JBOSS_HOME_$I`
  JBOSS_HOME=$( eval "echo \$$JBOSS_HOME" )
  PORT=8${I}80
  echo 'user=c5568adea472163dfc00c19c6348a665' >> $JBOSS_HOME/standalone/configuration/application-users.properties
  sed -i "s#</extensions>#</extensions>\n    <system-properties><property name=\"call.port\" value=\"${PORT}\"/></system-properties>#" \
    $JBOSS_HOME/standalone/configuration/standalone.xml
  sed -i "s#<core-environment>#<core-environment node-identifier=\"${I}\">#" $JBOSS_HOME/standalone/configuration/standalone.xml

  sed -i "s#\(^.*</socket-binding-group>\)#<outbound-socket-binding name=\"binding-remote-ejb-connection\">\n<remote-destination host=\"127.0.0.1\" port=\"${PORT}\"/>\n</outbound-socket-binding>\n\1#"\
    $JBOSS_HOME/standalone/configuration/standalone.xml
  sed -i "s#\(^.*<subsystem xmlns=\"urn:jboss:domain:remoting:.*\)#\1\n<outbound-connections>\n  <remote-outbound-connection name=\"remote-ejb-connection\" outbound-socket-binding-ref=\"binding-remote-ejb-connection\" username=\"user\" security-realm=\"PasswordRealm\" protocol=\"http-remoting\">\n    <properties>\n      <property name=\"SASL_POLICY_NOANONYMOUS\" value=\"false\"/>\n      <property name=\"SSL_ENABLED\" value=\"false\"/>\n    </properties>\n  </remote-outbound-connection>\n</outbound-connections>#"\
      $JBOSS_HOME/standalone/configuration/standalone.xml
  sed -i "s#\(^.*</security-realms>\)#<security-realm name=\"PasswordRealm\">\n  <server-identities>\n    <secret value=\"dXNlcg==\"/>\n  </server-identities>\n</security-realm>\n\1#"\
    $JBOSS_HOME/standalone/configuration/standalone.xml
done
```

. Then remove property `call.port` from `$JBOSS_HOME_3/standalone/configuration/standalone.xml`.
. If you want set logging of `com.arjuna` to `TRACE`. Useful really for `$JBOSS_HOME_2`

TIP: Could be useful to decrease interval of orphan safety interval
 (see _ArjunaJTA/jta/classes/com/arjuna/ats/jta/common/JTAEnvironmentBean.java_,
  default value for orphanSafetyInterval is 20000). Server settings should be
 `-Dcom.arjuna.ats.jta.orphanSafetyInterval=3000`

WARNING: For connection through outbound socket binding would be successful then
it's needed to have defined `jboss.node.name` during startup.

WARNING: If running with EAP 6.4 then you need to remove parameter `protocol` from configuration of
`remote-outbound-connection`. EAP 6.4 uses protocol `remote` and doesn't know other. That's reason why the
option for configuration of the protocol is not available. +
Plus by default `remoting` subsystem is not available in _EAP 6.4.x_ configuration
you will need to add it in version `1.2` (instead of `3.0` that it's in _EAP 7x_).


== To deploy

* `cp ejb-call-ear/target/ejb-call-ear.ear $JBOSS_HOME_1/standalone/deployments/8080.ear`
* `cp ejb-call-ear/target/ejb-call-ear.ear $JBOSS_HOME_2/standalone/deployments/8180.ear`
* `cp ejb-call-ear/target/ejb-call-ear.ear $JBOSS_HOME_3/standalone/deployments/8280.ear`

== To instrument

We will use byteman to instrument server crash. Add following to the end of the
`$JBOSS_HOME_2/bin/standalone.conf` file.

```
JAVA_OPTS="-javaagent:/opt/byteman-download-3.0.3/lib/byteman.jar=script:/home/ochaloup/tmp/byteman.btm -Djboss.modules.system.pkgs=org.jboss.byteman ${JAVA_OPTS}"
```

Now the byteman script is needed to be created at location `/home/ochaloup/tmp/byteman.btm`

[source, byteman]
```
# only a 'check' rule for we can see byteman is configured right
RULE say I am here
CLASS org.jboss.modules.Main
METHOD main
AT ENTRY
IF TRUE
DO
  System.out.println("Byteman is here");
ENDRULE

RULE crash on commit of testxa resource
CLASS org.jboss.qa.ochaloup.xa.TestXAResource
METHOD commit
AT ENTRY
IF true
DO
  System.out.println("Killing JVM"); killJVM();
ENDRULE

RULE crash on commit of basicaction
CLASS BasicAction
METHOD doCommit
AT ENTRY
IF true
DO
  debug("killing JVM: BasicAction"), killJVM()
ENDRULE
```

== To run

Run each of them with different settings (run on jdk8, at least for EAP7 :)

* `./bin/standalone.sh -Dcom.arjuna.ats.arjuna.recovery.periodicRecoveryPeriod=45 -Djboss.node.name=first`
* `./bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dcom.arjuna.ats.arjuna.recovery.periodicRecoveryPeriod=45 -Djboss.node.name=second`
* `./bin/standalone.sh -Djboss.socket.binding.port-offset=200 -Dcom.arjuna.ats.arjuna.recovery.periodicRecoveryPeriod=45 -Djboss.node.name=third`

Got to: http://localhost:8080/ejb-call-war and check the servers log output.
